name: Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: pip install --no-cache-dir -r requirements.txt

      - name: Install Pytest
        run: pip install pytest

      - name: Run Tests
        run: pytest  # Adjust this if you use another test runner

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: .  # Adjust the path if you would like to upload specific artifacts

  docker_build:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest